# test repop reply branch
base:
  cluster:
    type: vstart
    osd_cores: 8
    osd_devices:
    - /dev/nvme0n1
    - /dev/nvme1n1
    - /dev/nvme2n1
    - /dev/nvme3n1
    - /dev/nvme4n1
    - /dev/nvme5n1
    - /dev/nvme6n1
    - /dev/nvme7n1
    crimson: true
    seastore: true
    num_osds: 3
    osd_options:
      seastore_cache_lru_size: 1G
  workload:
    type: repeat
    runs: 5
    workload:
      type: fio_rbd
      pool_size: 3
      rbd_size: 50G
      fio_args:
        iodepth: 32
        rw: randwrite 
        bs: 4096
        numjobs: 4
        runtime: 60
        time_based: 1
overrides:
  randblock:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      osd_options:
        seastore_main_device_type: RANDOM_BLOCK_SSD
  delta:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      osd_options:
        seastore_data_delta_based_overwrite: 16384
  both:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      osd_options:
        seastore_main_device_type: RANDOM_BLOCK_SSD
        seastore_data_delta_based_overwrite: 16384
  normal:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      osd_options:
        seastore_main_device_type: SSD
