# test repop reply branch
base:
  cluster:
    source_directory: /home/sjust/wip-crimson-perf
    type: vstart
    osd_devices:
    - /dev/nvme4n1
    - /dev/nvme5n1
    - /dev/nvme6n1
    - /dev/nvme7n1
    - /dev/nvme0n1
    - /dev/nvme1n1
    - /dev/nvme2n1
    - /dev/nvme3n1
    num_osds: 3
  workload:
    type: fio_rbd
    pool_size: 1
    rbd_size: 10G
    num_pgs: 512
    num_clients: 32
    fio_args:
      iodepth: 32
      rw: randwrite 
      bs: 4096
      numjobs: 4
      runtime: 120
      time_based: 1
#  perfmonitors:
#  - type: perf
#  - type: counters
overrides:
  classic:
  all:
    cluster:
      crimson: true
      seastore: true
      osd_cores: 12
      crimson_balance_cpu: none
      osd_options:
        seastore_max_concurrent_transactions: 128
        seastore_cache_lru_size: 1G
