# test converting all assert to ceph_assert
base:
  cluster:
    taskset: '0-31:2'
    source_directory: /home/sjust/wip-crimson-perf
    crimson: true
    seastore: true
    crimson_balance_cpu: none
    osd_cores: 16
    source_directory: /home/sjust/wip-crimson-perf
    type: vstart
    osd_devices:
    - /dev/nvme4n1
    - /dev/nvme5n1
    - /dev/nvme6n1
    - /dev/nvme7n1
    - /dev/nvme0n1
    - /dev/nvme1n1
    - /dev/nvme2n1
    - /dev/nvme3n1
    num_osds: 1
    osd_options:
      seastore_max_concurrent_transactions: 128
      seastore_cache_lru_size: 2G
  workload:
    taskset: '1-32:2'
    type: fio_rbd
    pool_size: 1
    rbd_size: 10G
    rbd_prefill_size: 4K
    num_pgs: 512
    num_clients: 32
    fio_args:
      iodepth: 32
      rw: randwrite
      bs: 4096
      numjobs: 4
      runtime: 600
      time_based: 1
#  perfmonitors:
#  - type: perf
#  - type: counters
overrides:
  rbm:
    cluster:
      osd_options:
        seastore_main_device_type: RANDOM_BLOCK_SSD
  rbm-high-amplification:
    cluster:
      osd_options:
        seastore_main_device_type: RANDOM_BLOCK_SSD
        seastore_obj_data_write_amplification: 1000000
  rbm-delta:
    cluster:
      osd_options:
        seastore_data_delta_based_overwrite: 8192
        seastore_main_device_type: RANDOM_BLOCK_SSD
        seastore_obj_data_write_amplification: 1000000
  baseline:
