# test repop reply branch
base:
  cluster:
    type: vstart
    osd_cores: 8
    osd_devices:
    - /dev/nvme0n1
    - /dev/nvme1n1
    - /dev/nvme2n1
    - /dev/nvme3n1
    - /dev/nvme4n1
    - /dev/nvme5n1
    - /dev/nvme6n1
    - /dev/nvme7n1
    crimson: true
    seastore: true
    num_osds: 3
  workload:
    type: fio_rbd
    pool_size: 3
    rbd_size: 50G
    num_pgs: 512
    fio_args:
      iodepth: 32
      rw: randwrite 
      bs: 4096
      numjobs: 4
      runtime: 300
      time_based: 1
  perfmonitors:
#  - type: perf
  - type: counters
overrides:
  lru1G:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      crimson_balance_cpu: none
    osd_options:
      seastore_cache_lru_size: 1G
  transactions128:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      crimson_balance_cpu: none
    osd_options:
      seastore_max_concurrent_transactions: 128
  neither:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
  both:
    cluster:
      source_directory: /home/sjust/wip-crimson-perf
      crimson_balance_cpu: none
    osd_options:
      seastore_max_concurrent_transactions: 128
      seastore_cache_lru_size: 1G
