# test repop reply branch
base:
  cluster:
    crimson: true
    seastore: true
    crimson_balance_cpu: none
    osd_cores: 32
    source_directory: /home/sjust/wip-crimson-perf
    type: vstart
    osd_devices:
    - /dev/nvme4n1
    - /dev/nvme5n1
    - /dev/nvme6n1
    - /dev/nvme7n1
    - /dev/nvme0n1
    - /dev/nvme1n1
    - /dev/nvme2n1
    - /dev/nvme3n1
    num_osds: 1
    osd_options:
      seastore_max_concurrent_transactions: 128
      seastore_cache_lru_size: 1G
  workload:
    type: fio_rbd
    pool_size: 1
    rbd_size: 10G
    num_pgs: 512
    num_clients: 32
    fio_args:
      iodepth: 32
      rw: randwrite 
      bs: 4096
      numjobs: 4
      runtime: 300
      time_based: 1
  perfmonitors:
  - type: perf
  - type: counters
overrides:
  perf:
  baseline:
    source_directory: /home/sjust/baseline
